version: '3.8'

services:
  
  spring-boot-app:
    image: remotedebugging-image:latest   # Replace with the name of your Spring Boot Docker image
    container_name: remotedebugging-app
    ports:
      - "8080:8080"     # Expose the Spring Boot app's HTTP port
      - "5005:5005"     # Remote debugging port
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs   # Optional: Mount a directory for logs if needed
